from openai import OpenAI
from colorama import init, Fore
from opik.integrations.openai import track_openai
from opik import track
import os

# Initialize colorama with auto-reset for colored output
init(autoreset=True)

# Configure the Opik project name
os.environ.setdefault("OPIK_PROJECT_NAME", "MobilePhoneChatbot")

# System prompt defining the behavior of the chatbot
SYSTEM_PROMPT = """
<<SYS>>
Your name is Rusha. You're a friendly assistant specialized in recommending mobile phones.
Available mobiles:
    - iPhone 13 Pro Max (256GB) - $1,099 
    - Samsung Galaxy S21 Ultra (256GB) - $1,199
    - Google Pixel 6 Pro (128GB) - $899
    - OnePlus 9 Pro (256GB) - $1,069
    - Xiaomi Mi 11 Ultra (256GB) - $1,199
    
Examples:
User: For how much can I get the iPhone 13 Pro Max?
Rusha: The iPhone 13 Pro Max (256GB) is priced at $1,099. Would you like to know more about its features or anything else?
<</SYS>>
"""

@track
def stream_generator(prompt: str) -> str:
    """
    Generates a streaming response from the OpenAI API based on the provided prompt.
    
    Args:
        prompt (str): The formatted input prompt for the model.
    
    Returns:
        str: The complete response text generated by the model.
    """
    try:
        # Initialize the OpenAI client with tracking
        client = track_openai(
            OpenAI(
                base_url="http://192.168.1.194:8950/v1",
                api_key="tom",
            )
        )

        # Print the user's input in yellow
        print(Fore.LIGHTYELLOW_EX + f"User: {prompt.strip()}")

        # Generate a streaming response from the model
        response = client.chat.completions.create(
            model="gamma-2-2b-Instruct.gguf",
            messages=[
                {"role": "user", "content": prompt}
            ],
            stream=True,
            max_tokens=500,
            temperature=0.0,
            stop=["User:", "Rusha:", "[INST]", "<</SYS>>"]
        )

        # Stream and display the response in cyan
        response_text = ""
        print(Fore.LIGHTCYAN_EX + "Rusha:", end=" ")
        for chunk in response:
            if chunk.choices[0].delta.content:
                content = chunk.choices[0].delta.content
                response_text += content
                print(Fore.LIGHTCYAN_EX + content, end="", flush=True)
        print()  # Add a newline after the response
        return response_text

    except Exception as e:
        # Handle errors gracefully and print them in red
        print(Fore.RED + f"\nAn error occurred: {str(e)}")
        return ""

def format_prompt(user_input: str) -> str:
    """
    Formats the user input into a structured prompt for the model.
    
    Args:
        user_input (str): The raw input from the user.
    
    Returns:
        str: The formatted prompt including the system instructions.
    """
    return (
        f"{SYSTEM_PROMPT}\n"
        f"[INST] {user_input.strip()} [/INST]\n"
        f"Rusha:"
    )

if __name__ == "__main__":
    # Get user input and process it
    user_input = input("Enter your question: ")
    formatted_prompt = format_prompt(user_input)
    stream_generator(formatted_prompt)